# Generated by Django 5.0.7 on 2024-07-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goalcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalcompany',
            options={'verbose_name': 'Goal Company', 'verbose_name_plural': 'Goal Companies'},
        ),
        migrations.AlterField(
            model_name='goalcompany',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='goal/company'),
        ),
        migrations.AlterField(
            model_name='goalcompany',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='goal/company'),
        ),
        migrations.CreateModel(
            name='OurViewsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('our_views', models.CharField(max_length=255)),
                ('our_mission', models.CharField(max_length=255)),
                ('our_corporate_culture', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Our vision and mission is our company',
                'verbose_name_plural': 'Our vision and mission is our company',
            },
        ),
    ]
