# Generated by Django 5.0.7 on 2024-07-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_goalcompany_options_alter_goalcompany_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorBoardCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_board_list', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Supervisor Board Company',
                'verbose_name_plural': 'Supervisor Board Companies',
            },
        ),
    ]
