# Generated by Django 5.0.7 on 2024-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lidershipcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='organizational/company/')),
            ],
            options={
                'verbose_name': 'Organizational Structure',
                'verbose_name_plural': 'Organizational Structures',
            },
        ),
    ]
