# Generated by Django 5.0.7 on 2024-07-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_aboutcompany_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalstructure',
            name='image',
        ),
        migrations.AddField(
            model_name='organizationalstructure',
            name='file',
            field=models.FileField(default='ss', upload_to='main_organizational/company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lidershipcompany',
            name='image',
            field=models.ImageField(upload_to='main_lidership/company'),
        ),
    ]
