# Generated by Django 5.0.7 on 2024-07-26 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_organizationalstructure_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatesCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('manzili', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'LIST OF AFFILIATES',
                'verbose_name_plural': 'LIST OF AFFILIATES',
            },
        ),
        migrations.CreateModel(
            name='AuditorsRepotsCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_auditors/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': "Auditor's Report",
                'verbose_name_plural': "Auditor's Reports",
            },
        ),
        migrations.CreateModel(
            name='BusinessPlanCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_business/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Business Plan',
                'verbose_name_plural': 'Business Plans',
            },
        ),
        migrations.CreateModel(
            name='CorporateDocumentsCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_corporate_documants/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Corporate Governance Document',
                'verbose_name_plural': 'Corporate Governance Documents',
            },
        ),
        migrations.CreateModel(
            name='DividendCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=255)),
                ('calculated_dividend', models.CharField(max_length=255)),
                ('paid_dividends', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
            },
        ),
        migrations.CreateModel(
            name='DutiesCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_duties/company')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Duties of the compliance service',
                'verbose_name_plural': 'Duties of the compliance services',
            },
        ),
        migrations.CreateModel(
            name='FactsCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default='2023-05-29')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('file', models.FileField(upload_to='main_facts/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Important Fact',
                'verbose_name_plural': 'Important Facts',
            },
        ),
        migrations.CreateModel(
            name='FinancialCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_financial/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Financial and Economic Status Indicator',
                'verbose_name_plural': 'Financial and Economic Status Indicators',
            },
        ),
        migrations.CreateModel(
            name='IssueOfSecuritiesCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_security/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Issue of Security',
                'verbose_name_plural': 'Issue of Securities',
            },
        ),
        migrations.CreateModel(
            name='LaborProtectionCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_labor/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Labor protection and technical safety',
                'verbose_name_plural': 'Labor protection and technical safeties',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='news/news_images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='main.news')),
            ],
            options={
                'verbose_name': 'News image',
                'verbose_name_plural': 'News images',
            },
        ),
        migrations.CreateModel(
            name='PurchasePlanCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=244)),
                ('file', models.FileField(upload_to='main_purchase/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Purchase Plan',
                'verbose_name_plural': 'Purchase Plans',
            },
        ),
        migrations.CreateModel(
            name='RegulationCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_regulation/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Regulation',
                'verbose_name_plural': 'Regulations',
            },
        ),
        migrations.CreateModel(
            name='ReportCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=244)),
                ('file', models.FileField(upload_to='main_report/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='ResultVotingCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_result/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Result of voting',
                'verbose_name_plural': 'Results of voting',
            },
        ),
        migrations.CreateModel(
            name='ShareholdersCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='main_regulation/corporate')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'MEETING OF SHAREHOLDER',
                'verbose_name_plural': 'MEETING OF SHAREHOLDERS',
            },
        ),
        migrations.CreateModel(
            name='TenderCorporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('tender_id', models.IntegerField()),
                ('price', models.FloatField()),
                ('link', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
            },
        ),
    ]
