# Generated by Django 5.0.7 on 2024-07-27 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_affiliatescorporate_auditorsrepotscorporate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dvigatel nomi')),
                ('type', models.CharField(choices=[('CSS_PRIME', 'CSS PRIME'), ('STANDARD', 'Standart')], default='STANDARD', max_length=20, verbose_name='Dvigatel turi')),
                ('cylinder_volume', models.FloatField(verbose_name='Silindr hajmi, L')),
                ('cylinder_spacing', models.IntegerField(verbose_name='Silindrlar orasidagi masofa, mm')),
                ('cylinder_diameter', models.FloatField(verbose_name='Silindr diametri, mm')),
                ('piston_stroke', models.FloatField(verbose_name="Porshen yo'li, mm")),
                ('compression_ratio', models.FloatField(verbose_name='Siqish darajasi')),
                ('number_of_cylinders', models.IntegerField(verbose_name='Silindrlar soni')),
                ('valves_per_cylinder', models.IntegerField(verbose_name='Har bir silindrdagi klapanlar soni')),
                ('max_torque', models.FloatField(verbose_name='Maksimal aylanish momenti, Nm')),
                ('max_power', models.FloatField(verbose_name='Maksimal quvvati, kW')),
                ('fuel_consumption', models.FloatField(verbose_name="Yoqilg'i sarfi, L/100km")),
                ('weight', models.FloatField(verbose_name="Dvigatel og'irligi, kg")),
                ('dimensions', models.CharField(max_length=50, verbose_name="Dvigatel o'lchamlari (U/K/B), mm")),
                ('emission_standard', models.CharField(max_length=20, verbose_name='Emissiya standarti')),
                ('recommended_octane', models.IntegerField(verbose_name='Taklif qilingan benzin oktan raqami')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Dvigatel',
                'verbose_name_plural': 'Dvigatellar',
            },
        ),
    ]
