# Generated by Django 5.0.7 on 2024-07-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='image',
            field=models.ImageField(default='da', upload_to='products/image'),
            preserve_default=False,
        ),
    ]
