# Generated by Django 5.0.7 on 2024-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_goalcompany_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lidershipcompany',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
