# Generated by Django 5.0.7 on 2024-08-01 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_energymanagmentsystemcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomanBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'WomanBoard',
                'verbose_name_plural': 'WomanBoard',
            },
        ),
        migrations.CreateModel(
            name='WomanBoardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='woman/womanboard_images/')),
                ('womanboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='womanboard_images', to='main.news')),
            ],
            options={
                'verbose_name': 'WomanBoard image',
                'verbose_name_plural': 'WomanBoard images',
            },
        ),
    ]
